version: 1.0.{build}
install:
  - ps: choco install hugo
build_script:
  - hugo -d C:\projects\mattmurbach-com\public\
artifacts:
  - path: public\*
    name: public_website
environment:
  DEV_BUCKET: mattmurbach.com
  AWS_ACCESS_KEY_ID:
    secure: 5u0pzpll1lcn65y6DqXTEs7PzLwLh99J4GZkDAvMhPU=
  AWS_SECRET_ACCESS_KEY:
    secure: 89s8cVhLnaOUSm5unh5aeX0//9chlBJFyHo/+zFCvOKNy9TSMZPP92Aj7sMZNmC7
after_test:
  - ps: $root = Resolve-Path .\public; [IO.Directory]::GetFiles($root.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ -FileName $_.Substring($root.Path.Length + 1) -DeploymentName to-publish }
deploy:
- provider: S3
  access_key_id: $(AWS_ACCESS_KEY_ID)
  secret_access_key: $(AWS_SECRET_ACCESS_KEY)
  bucket: $(DEV_BUCKET)
  region: us-west-2
  set_public: true
  artifacts: to-publish
  on:
     appveyor_repo_tag: true
